(cl:defpackage beginner_tutorials-msg
  (:use )
  (:export
   "<NUM>"
   "NUM"
   "<GOTOFEEDBACK>"
   "GOTOFEEDBACK"
   "<GOTORESULT>"
   "GOTORESULT"
   "<GOTOACTION>"
   "GOTOACTION"
   "<GOTOACTIONRESULT>"
   "GOTOACTIONRESULT"
   "<GOTOGOAL>"
   "GOTOGOAL"
   "<GOTOACTIONGOAL>"
   "GOTOACTIONGOAL"
   "<GOTOACTIONFEEDBACK>"
   "GOTOACTIONFEEDBACK"
  ))

