; Auto-generated. Do not edit!


(cl:in-package beginner_tutorials-msg)


;//! \htmlinclude GotoGoal.msg.html

(cl:defclass <GotoGoal> (roslisp-msg-protocol:ros-message)
  ((dest
    :reader dest
    :initarg :dest
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass GotoGoal (<GotoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GotoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GotoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name beginner_tutorials-msg:<GotoGoal> is deprecated: use beginner_tutorials-msg:GotoGoal instead.")))

(cl:ensure-generic-function 'dest-val :lambda-list '(m))
(cl:defmethod dest-val ((m <GotoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader beginner_tutorials-msg:dest-val is deprecated.  Use beginner_tutorials-msg:dest instead.")
  (dest m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GotoGoal>) ostream)
  "Serializes a message object of type '<GotoGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'dest) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GotoGoal>) istream)
  "Deserializes a message object of type '<GotoGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'dest) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GotoGoal>)))
  "Returns string type for a message object of type '<GotoGoal>"
  "beginner_tutorials/GotoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GotoGoal)))
  "Returns string type for a message object of type 'GotoGoal"
  "beginner_tutorials/GotoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GotoGoal>)))
  "Returns md5sum for a message object of type '<GotoGoal>"
  "ca84cfd23a695b47e5a57b41e6a056a6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GotoGoal)))
  "Returns md5sum for a message object of type 'GotoGoal"
  "ca84cfd23a695b47e5a57b41e6a056a6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GotoGoal>)))
  "Returns full string definition for message of type '<GotoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/PoseStamped dest  # Specify which dishwasher we want to use~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GotoGoal)))
  "Returns full string definition for message of type 'GotoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%geometry_msgs/PoseStamped dest  # Specify which dishwasher we want to use~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GotoGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'dest))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GotoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GotoGoal
    (cl:cons ':dest (dest msg))
))
